### ISSUE TITLE
[QnA] 홈 탭바에 동네생활, 내근처, 채팅, 나의 당근을 추가해야하는데 영어 이름 추천해주세요...

### ISSUE THREAD

**Issue by mingging** [donnyrla10/DaangnMarketClone#2]
홈 탭바에 홈이랑 동네생활이랑 내 근처, 채팅 나의 당근이 있는데...
제가 영어를 못해서.... 영어이름 변수 추천해주세요;......
특히 동네생활....

**Comment by donnyrla10** [comment]
동네 생활 -> townLife, villageLife 어떠세요 빌리지가 더 귀여운것 같은데..ㅎ
내 근처 -> nearBy
채팅 -> chat
나의 당근 -> myCarrot

과연.. 무엇을 선택할건가요^_^

**Comment by mingging** [comment]
헐 당신 천재야..? 
저 동네생활 빌리지라이프 한표요! 진짜 빌리지가 뭔가.. 그 .. 오잉포잉하고.. 퐁팡핑하는.. 그런 뭔가 포근한 느낌이 있어요..
